### ISSUE TITLE
some pokemon show up twice in pokemon list

### ISSUE THREAD

**Issue by v-tur** [304-project/pokedex#8]
it's because some pokemon have two types, so they're included twice in the list because of the join.
e.g. zubat is both poison and a flying type.

maybe just restrict pokemon to only having one type, or remove duplicates in sql

**Comment by pahulpanesar** [comment]
Can we fix this by changing the sql script to only have 1 type per pokemon?

**Comment by v-tur** [comment]
yeah i'll fix
